# NumPy 2D array
    Problem Statement:
    Given a 2D list, create a numpy 2D array using it.
    Note: Given 2D list is [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
    Print the Numpy array.
    Output Format :
    numpyArray

In [1]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np

ndList = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(np.array(ndList))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# NumPy 0s and 1s
    Problem Statement:
    Create an integer array of size 10, where all the values should be 0 but the fifth value should be 1.
    Print the elements of array.
    Output Format :
    element1 element2 element3 ... 

In [3]:
## Open and read data file as specified in the question
## Print the required output in given format

## Print the required output in given format
import numpy as np

h=np.zeros(10,dtype=int)
h[4]=1
for i in h:
    print(i,end=' ')

0 0 0 0 1 0 0 0 0 0 

# NumPy Inclusive
    Problem Statement:
    Create an array with values ranging consecutively from 9 to 49 (both inclusive).
    Print the Numpy array.
    Output Format :
    element1 element2 element3 ...

In [4]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np

h=np.arange(9,50)
for i in h:
    print(i,end=' ')

9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 

# Identity Matrix
    Problem Statement:
    Create a matrix having diagonal elements as 1 and all other elements as 0 of size (5, 6).
    Print the Numpy array.
    Output Format :
    numpyArray

In [5]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np

h=np.eye(5,6,dtype=int)

print(h)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


# Cut the Rope
    Problem Statement:
    You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length.
    Note:Array elements are the points where cut is to be made and round upto 2 decimal place.
    Print the array element.
    Output Format :
    element1 
    element2 
    element3
    .
    .ipynb_checkpoints/

In [6]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
a = np.linspace(0,5,10)[1:9]
for i in a:
    print(round(i,2))


0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44


# Print Elements
    Given a 2D integer array size (4, 5) with name input_?
    Print elements of highlighted matrix
    Output Format :
    element1 element2 element3 . . .
    element1 element2 element3 . . .
    element1 element2 element3 . . .
    element1 element2 element3 . . .ipynb_checkpoints/

In [7]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)
for i in input_[2,:3]:
    print(i,end=' ')
print()
for i in input_[1:,3]:
    print(i,end=' ')
print()
for i in input_[2:]:
    for j in i:
        print(j,end=' ')
print()
for i in input_[1:3,1:3]:
    for j in i:
        print(j,end=' ')


11 12 13 
9 14 19 
11 12 13 14 15 16 17 18 19 20 
7 8 12 13 

# Non-Zero elements
    Problem Statemnt:
    Find indices of non-zero elements from the array [1,2,0,0,4,0] ?
    Print the index of non-zero elements.
    Output Format :
    index1 index2 index3 ... 


In [8]:
## Open and read data file as specified in the question
## Print the required output in given format

import numpy as np
a=[1,2,0,0,4,0]
for i in np.nonzero(a)[0]:
    print(i,end=' ')


0 1 4 

# Multiples of 3
    Problem Statement:
    Given an integer array of size 10. Print the index of elements which are multiple of 3.
    Note: Generate the following array
    array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
    Print the index of elements.
    Output Format :
    index1 index2 index3 ... 

In [9]:
## Open and read data file as specified in the question
## Print the required output in given format

import numpy as np

arr=np.array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
for i in np.where(arr % 3 == 0)[0]:
    print(i,end=' ')

1 4 7 

# Odd elements
    Problem Statemnt:
    Given an integer array of size 10. Replace the odd number in numpy array with -1 ?
    Note: Generate the following array
    array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    Print the Numpy array.
    Output Format :
    firstElement secondElement  ... 

In [12]:
## Open and read data file as specified in the question
## Print the required output in given format

import numpy as np

arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[arr%2!=0]=-1
for i in arr:
    print(i,end=' ')
    

-1 2 -1 4 -1 6 -1 8 -1 10 

# Replace Max
    Problem Statemnt:
    Given an integer array of size 9 and replace the first occurrence of maximum value by 0?
    Note: Generate the following array
    array([11, 2, 13, 4, 15, 6, 27, 8, 19])
    Print the Numpy array.
    Output Format :
    firstElement
    secondElement 
    ... 


In [13]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
arr=np.array([11, 2, 13, 4, 15, 6, 27, 8, 19])
arr[np.argmax(arr)]=0
for i in arr:
    print(i)

11
2
13
4
15
6
0
8
19


# Negate Elements
    Problem Statemnt:
    Given a 1D array, negate all elements which are between 3 and 8 (both inclusive)?
    Note: Generate the following array
    array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    Print the Numpy array.
    Output Format :
    firstElement 
    secondElement  
    ... 

In [14]:
## Open and read data file as specified in the question
## Print the required output in given format

import numpy as np
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[(arr>=3)&(arr<=8)]*=-1
for i in arr:
    print(i)

1
2
-3
-4
-5
-6
-7
-8
9
10


# Height
    Problem Statemnt:
    Given age and height of 20 students in two different numpy arrays with name age and height (in cms). Print the age of those students whose height is above 155 cm.
    Print the Numpy array.
    Output Format :
    age1 height1 
    age2 height2 
    ... 


In [15]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])

np_age=age[height>155]
np_heigth=height[height>155]

for i in range(len(np_heigth)):
    print(np_age[i],np_heigth[i])


15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172


# Sort by column
    Problem Statemnt:
    Sort a given 2D array of shape (4, 5) by 2nd column (i.e. column at index 1) in ascending order.
    That means, we should re-arrange complete row based on 2nd columns' values.
    Given 2D array is:
     [[21 20 19 18 17]
      [16 15 14 13 12]
      [11 10  9  8  7]
      [ 6  5  4  3  2]]
    Print the 2D array in sorted order.
    Note you have to generate the 2D Array.Here 2nd column means column present at index 1.
    Output Format :
    [[ 6  5  4  3  2]
    [11 10  9  8  7]
    [16 15 14 13 12]
    [21 20 19 18 17]]

In [17]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np


arr=np.array([[21 ,20, 19, 18, 17],
                [16, 15, 14, 13, 12],
                [11 ,10 , 9 , 8 , 7],
                [ 6 , 5 , 4  ,3 , 2]])

print(np.sort(arr,axis=0))



[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


# Killed in USA
    Given file "terrorismData.csv"
    It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
    Problem Statement :
    Find value of killed column only where country == ‘United States’?
    Print 0 in place of missing values.
    Print count of Killed as integer value.
    Output Format :
    Killed1
    Killed2
    Killed3
    Killed4
    . . .
    . . .
    . . .ipynb_checkpoints/

In [ ]:
import numpy as np
import csv

file=open("terrorismData.csv")
data=csv.DictReader(file,skipinitialspace=True)
killed=[]
country=[]

for row in data:
    killed.append(row['Killed'])
    country.append(row['Country'])
    
np_killed=np.array(killed)
np_killed[np_killed=='']='0.0'

np_killed=np.array(np_killed,dtype=float)
np_country=np.array(country)
b=np_country=='United States'
ans=np_killed[b]

for i in ans:
    print(int(i))

# Total Killed in USA
    Given file "terrorismData.csv"
    It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
    Problem Statement :
    Find total number of people killed from USA?
    Note: Some columns of killed are empty so replace them by 0.
    Print count of Killed as integer value.
    Output Format :
    TotalKilled

In [25]:
import numpy as np
import csv

file=open("terrorismData.csv")
data=csv.DictReader(file,skipinitialspace=True)
killed=[]
country=[]

for row in data:
    killed.append(row['Killed'])
    country.append(row['Country'])
    
np_killed=np.array(killed)
np_killed[np_killed=='']='0.0'

np_killed=np.array(np_killed,dtype=float)
np_country=np.array(country)
b=np_country=='United States'
ans=np_killed[b]

print(int(np.sum(ans)))

# Terrorism Day
    Given file "terrorismData.csv"
    It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
    Problem Statement :
    Find the number of attack held between day 10 and day 20?(ignoring the year and month)(including both day)
    Print count of NumberOFAttack as integer value.
    Output Format :
    country

In [ ]:
import numpy as np
import csv

file=open("terrorismData.csv")
data=csv.DictReader(file,skipinitialspace=True)
Day=[]

for row in data:
    Day.append(row['Day'])
    
np_Day=np.array(Day,dtype=int)
np_bool =(np_Day>=10) &(np_Day<=20)

print(np.sum(np_bool))

# Terrorism Date
    Given file "terrorismData.csv"
    It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
    Problem Statement :
    Find the number of attack held between 1 Jan 2010 and 31 Jan 2010?(including both date).
    Note Ignore the case where day is 0
    Print count of NumberOFAttack as integer value.
    Output Format :
    count


In [ ]:
import numpy as np
import csv

file=open("terrorismData.csv")
data=csv.DictReader(file,skipinitialspace=True)
Day=[]
Month=[]
Year=[]

for row in data:
    Day.append(row['Day'])
    Month.append(row['Month'])
    Year.append(row['Year'])
    
np_Day=np.array(Day,dtype=int)
np_Month=np.array(Month,dtype=int)
np_Year=np.array(Year,dtype=int)

np_bool =(np_Day>=1) &(np_Day<=31) & (np_Year==2010) &(np_Month==1)

print(np.sum(np_bool))

# Terror Casualty Attack
    Given file "terrorismData.csv"
    It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
    Problem Statement :
    As we knew the Kargil ( in Jammu and Kashmir) War that took place between May 1999 and July 1999 (3 Months) ,so there was a huge conflict in Kashmir Valley during this period.
    In this dataset, there is no information regarding the war between the two countries to find out the casualty during the war.
    So find out the attack in this period in which maximum casualties happened.
    Print the count of casualties (as integer), city in which that attack happened and name of attack group.
    Note : Casualty = Killed + Wounded.Fill the empty value in killed or wounded feature to 0.
    Output Format :
    Casualty City TerroristGroup

In [ ]:



# Open and read data file as specified in the question
# Print the required output in given format
import numpy as np
import csv
with open('terrorismData.csv', encoding = "utf-8") as file_obj:
    file_data=csv.DictReader(file_obj,skipinitialspace=True)
    wounded=[]
    killed=[]
    grp=[]
    city=[]
    for row in file_data:
        if row['Year']=='1999':
             if row["Month"]=="5" or row["Month"]=="6" or row["Month"]=="7":
                    if row['State']=='Jammu and Kashmir':
                            if "Unknown" not in row["City"]:
                                if "Unknown" not in row["Group"]:
                                    killed.append(row['Killed'])
                                    wounded.append(row['Wounded'])
                                    city.append(row['City'])
                                    grp.append(row['Group'])
killed = np.array(killed)
wounded = np.array(wounded)
city = np.array(city)
grp=np.array(grp)
 
killed[killed == ""] = "0.0"
wounded[wounded == ""] = "0.0"
killed = np.array(killed, dtype = float)
wounded = np.array(wounded, dtype = float)
# taking sum and then printing the required values
casualty = (killed + wounded)
max_casualty = (int)(casualty.max())
# getting the INDEX of max casualty, this is for putting the required index in city and group
max_casualty_arg = casualty.argmax()
print(max_casualty,city[max_casualty_arg],grp[max_casualty_arg])


# Terror Casualty Red
    Given file "terrorismData.csv"
    It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
    Problem Statement :
    Find the casualty in the Red Corridor States ? Mainly Red corridor states include Jharkhand, Odisha, Andhra Pradesh, and Chhattisgarh.
    Note: Casualty=Killed +Wounded
    Print count of Casualty as integer value.
    Output Format :
    Count


In [ ]:
import numpy as np
import csv

file=open("terrorismData.csv")
data=csv.DictReader(file,skipinitialspace=True)
State=[]
Killed=[]
Wounded=[]


for row in data:
    State.append(row['State'])
    Killed.append(row['Killed'])
    Wounded.append(row['Wounded'])
    
np_killed=np.array(Killed)
np_killed[np_killed=='']='0.0'
np_killed=np.array(np_killed,dtype=float)

np_Wounded=np.array(Wounded)
np_Wounded[np_Wounded=='']='0.0'
np_Wounded=np.array(np_Wounded,dtype=float)

Casualty = np.array(np_killed+np_Wounded,dtype=int)
    
np_State=np.array(State)    

np_bool =(np_State =='Jharkhand') | (np_State=='Odisha') |(np_State=='Andhra Pradesh')|(np_State=='Chhattisgarh')

print(sum(Casualty[np_bool]))

# Terror City Casualty
    Given file "terrorismData.csv"
    It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
    Problem Statement :
    Find top 5 Indian Cities which has most number of casualties ?
    Print top 5 cities along with total casualties in that city. Print count of Casualty as integer value.
    Note: Ignoring the City which is Unknown.
    Casualty = Killed + Wounded.
    Output Format :
    city_1 casualty_1
    city_2 casualty_2
    city_3 casualty_3
    city_4 casualty_4
    city_5 casualty_5

In [28]:
import numpy as np
import csv

with open('terrorismData.csv', encoding='utf8') as file_obj:
    file_data=csv.DictReader(file_obj, skipinitialspace=True)
    killed=[]
    wounded=[]
    city=[]
    for row in file_data:
        if 'India' in row['Country'] and 'Unknown' not in row['City']:
            city.append(row['City'])
            wounded.append(row['Wounded'])
            killed.append(row['Killed'])
    np_wounded=np.array(wounded)
    np_killed=np.array(killed)
    np_city=np.array(city)
    
    np_killed[np_killed=='']='0.0'
    np_wounded[np_wounded=='']='0.0'
    np_killed=np.array(np_killed, dtype='float')
    np_wounded=np.array(np_wounded, dtype='float')
    np_casuality=np.array(np_wounded+np_killed, dtype='int')
    citydic={}
    for i in range(len(np_city)):
        if np_city[i] in citydic:
            citydic[np_city[i]]+=np_casuality[i]
        else:
            citydic[np_city[i]]=np_casuality[i]
    
    count=0
    city=''
    for i in citydic:
        if citydic[i]>count:
            count=citydic[i]
            city=i
    print(city, count)
    del citydic[city]
    
    count=0
    city=''
    for i in citydic:
        if citydic[i]>count:
            count=citydic[i]
            city=i
    print(city, count)
    del citydic[city]
    
    count=0
    city=''
    for i in citydic:
        if citydic[i]>count:
            count=citydic[i]
            city=i
    print(city, count)
    del citydic[city]
    
    count=0
    city=''
    for i in citydic:
        if citydic[i]>count:
            count=citydic[i]
            city=i
    print(city, count)
    del citydic[city]
    
    count=0
    city=''
    for i in citydic:
        if citydic[i]>count:
            count=citydic[i]
            city=i
    print(city, count)
    del citydic[city]


Srinagar 3134
New Delhi 2095
Mumbai 2016
Jammu 1119
Guwahati 822


# Terrorism FrequentDay
    Given file "terrorismData.csv"
    It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
    Problem Statement :
    Find the most frequent day of attack in a terrorismDataset ?
    Note: Here np.unique can be used.
    Print count of frequent day and number of attack as Integer value.
    Output Format :
    Day NumberOFAttack


In [27]:
## Open and read data file as specified in the question
## Print the required output in given format

import numpy as np
import csv

with open('terrorismData.csv', encoding='utf8') as file_obj:
    file_data=csv.DictReader(file_obj, skipinitialspace=True)
    
    day=[]
    for row in file_data:
        day.append(row['Day'])
    np_day=np.array(day, dtype='int')
    day, count=np.unique(np_day, return_counts=True)
    print(day[np.argmax(count)], count[np.argmax(count)])

15 6500
